import { ComplaintCategory, Neighborhood, RequestType, ComplaintStatus } from './types';

export const MERLO_MAP_CONFIG = {
  center: [-34.6653, -58.7292] as [number, number], // Merlo Centro
  defaultZoom: 13,
  minZoom: 11,
  maxZoom: 18,
  bounds: [
    [-34.8000, -58.8500], // Southwest
    [-34.6200, -58.6200], // Northeast
  ] as [[number, number], [number, number]],
};

export const NEIGHBORHOODS: Neighborhood[] = [
  {
    id: 'n-1',
    name: 'Merlo Centro',
    slug: 'merlo-centro',
    postalCode: '1722',
    latitude: -34.6653,
    longitude: -58.7292,
    description: 'Casco histórico, zona comercial y estación Merlo',
  },
  {
    id: 'n-2',
    name: 'San Antonio de Padua',
    slug: 'san-antonio-de-padua',
    postalCode: '1718',
    latitude: -34.6702,
    longitude: -58.6974,
    description: 'Zona residencial y comercial de Padua',
  },
  {
    id: 'n-3',
    name: 'Libertad',
    slug: 'libertad',
    postalCode: '1716',
    latitude: -34.7001,
    longitude: -58.6833,
    description: 'Localidad de Libertad y barrios aledaños',
  },
  {
    id: 'n-4',
    name: 'Parque San Martín',
    slug: 'parque-san-martin',
    postalCode: '1722',
    latitude: -34.6850,
    longitude: -58.7350,
    description: 'Barrio Parque San Martín',
  },
  {
    id: 'n-5',
    name: 'Pontevedra',
    slug: 'pontevedra',
    postalCode: '1761',
    latitude: -34.7450,
    longitude: -58.6950,
    description: 'Localidad de Pontevedra, zona sur de Merlo',
  },
  {
    id: 'n-6',
    name: 'Mariano Acosta',
    slug: 'mariano-acosta',
    postalCode: '1723',
    latitude: -34.7200,
    longitude: -58.7900,
    description: 'Localidad de Mariano Acosta',
  },
  {
    id: 'n-7',
    name: 'Agustín Ferrari',
    slug: 'agustin-ferrari',
    postalCode: '1723',
    latitude: -34.6980,
    longitude: -58.7650,
    description: 'Barrio Agustín Ferrari',
  },
  {
    id: 'n-8',
    name: 'Pompeya',
    slug: 'pompeya',
    postalCode: '1722',
    latitude: -34.6750,
    longitude: -58.7450,
    description: 'Barrio Pompeya y Merlo Norte',
  },
  {
    id: 'n-9',
    name: 'Santa Marta',
    slug: 'santa-marta',
    postalCode: '1722',
    latitude: -34.6920,
    longitude: -58.7180,
    description: 'Barrio Santa Marta',
  },
  {
    id: 'n-10',
    name: 'Arco Iris',
    slug: 'arco-iris',
    postalCode: '1722',
    latitude: -34.6780,
    longitude: -58.7100,
    description: 'Barrio Arco Iris',
  },
  {
    id: 'n-11',
    name: 'Matera',
    slug: 'matera',
    postalCode: '1722',
    latitude: -34.6900,
    longitude: -58.7600,
    description: 'Barrio Matera y alrededores',
  },
  {
    id: 'n-12',
    name: 'Los Aromos',
    slug: 'los-aromos',
    postalCode: '1761',
    latitude: -34.7300,
    longitude: -58.7150,
    description: 'Barrio Los Aromos',
  },
  {
    id: 'n-13',
    name: 'Rivadavia',
    slug: 'rivadavia',
    postalCode: '1716',
    latitude: -34.6880,
    longitude: -58.6990,
    description: 'Barrio Rivadavia',
  },
];

export const COMPLAINT_CATEGORIES: ComplaintCategory[] = [
  {
    id: 'cat-1',
    name: 'Alumbrado público',
    slug: 'alumbrado-publico',
    icon: 'Lightbulb',
    color: '#D97706',
    description: 'Luminarias apagadas, cables cortados, postes en mal estado',
  },
  {
    id: 'cat-2',
    name: 'Calles y baches',
    slug: 'calles-y-baches',
    icon: 'Construction',
    color: '#0B4F8A',
    description: 'Baches, pozos, roturas de asfalto o calles de tierra intransitables',
  },
  {
    id: 'cat-3',
    name: 'Recolección de residuos',
    slug: 'recoleccion-residuos',
    icon: 'Trash2',
    color: '#10B981',
    description: 'Falta de recolección, microbasurales y contenedores desbordados',
  },
  {
    id: 'cat-4',
    name: 'Inundaciones y desagües',
    slug: 'inundaciones-desagues',
    icon: 'CloudRain',
    color: '#2563EB',
    description: 'Zanjas tapadas, bocas de tormenta obstruidas, anegamientos pluviales',
  },
  {
    id: 'cat-5',
    name: 'Limpieza y mantenimiento',
    slug: 'limpieza-mantenimiento',
    icon: 'Sparkles',
    color: '#0EA5E9',
    description: 'Poda de árboles peligrosos, desmalezado y limpieza urbana',
  },
  {
    id: 'cat-6',
    name: 'Seguridad ciudadana',
    slug: 'seguridad-ciudadana',
    icon: 'ShieldAlert',
    color: '#EF4444',
    description: 'Puntos oscuros peligrosos, cámaras fuera de servicio o reclamos de patrullaje',
  },
  {
    id: 'cat-7',
    name: 'Espacios verdes y plazas',
    slug: 'espacios-verdes',
    icon: 'Trees',
    color: '#059669',
    description: 'Juegos infantiles rotos, plazas descuidadas, falta de bancos',
  },
  {
    id: 'cat-8',
    name: 'Tránsito y señalización',
    slug: 'transito-senalizacion',
    icon: 'Car',
    color: '#0284C7',
    description: 'Semáforos rotos, reductores de velocidad necesarios, señalética vial',
  },
  {
    id: 'cat-9',
    name: 'Transporte público',
    slug: 'transporte-publico',
    icon: 'Bus',
    color: '#EC4899',
    description: 'Paradas sin refugio, frecuencias deficientes o problemas de recorridos',
  },
  {
    id: 'cat-10',
    name: 'Salud',
    slug: 'salud',
    icon: 'HeartPulse',
    color: '#DC2626',
    description: 'Salas de primeros auxilios (CAPS), falta de insumos médicos o atención',
  },
  {
    id: 'cat-11',
    name: 'Educación',
    slug: 'educacion',
    icon: 'GraduationCap',
    color: '#0284C7',
    description: 'Infraestructura de escuelas, veredas escolares y seguridad de acceso',
  },
  {
    id: 'cat-12',
    name: 'Accesibilidad',
    slug: 'accesibilidad',
    icon: 'Accessibility',
    color: '#0B4F8A',
    description: 'Rampas para discapacitados faltantes, veredas rotas e intransitables',
  },
  {
    id: 'cat-13',
    name: 'Otros reclamos',
    slug: 'otros',
    icon: 'HelpCircle',
    color: '#64748B',
    description: 'Otras problemáticas barriales que afectan a los vecinos de Merlo',
  },
];

export const REQUEST_TYPES: { type: RequestType; label: string; description: string; icon: string }[] = [
  {
    type: 'reclamo',
    label: 'Reclamo vecinal',
    description: 'Reportar una falla en servicios o desatención de problemáticas vecinales',
    icon: 'AlertTriangle',
  },
  {
    type: 'infraestructura',
    label: 'Problema de infraestructura',
    description: 'Baches, luminarias, zanjas, obras inconclusas o roturas de pavimentación',
    icon: 'Wrench',
  },
  {
    type: 'irregularidad',
    label: 'Denuncia o irregularidad',
    description: 'Microbasurales clandestinos, ocupaciones ilegales o fallas normativas',
    icon: 'FileWarning',
  },
  {
    type: 'sugerencia',
    label: 'Sugerencia',
    description: 'Ideas de mejora para el funcionamiento de servicios barriales',
    icon: 'Lightbulb',
  },
  {
    type: 'propuesta',
    label: 'Propuesta comunitaria',
    description: 'Iniciativas y proyectos de impacto positivo para los barrios de Merlo',
    icon: 'HandHeart',
  },
  {
    type: 'solicitud',
    label: 'Solicitud de intervención',
    description: 'Pedido de articulación comunitaria o relevamiento en el territorio',
    icon: 'ClipboardCheck',
  },
  {
    type: 'otro',
    label: 'Otro',
    description: 'Cualquier otra inquietud comunitaria no categorizada',
    icon: 'HelpCircle',
  },
];

export const COMPLAINT_STATUS_CONFIG: Record<
  ComplaintStatus,
  {
    label: string;
    description: string;
    color: string;
    bg: string;
    text: string;
    border: string;
    badgeClass: string;
    stepIndex: number;
  }
> = {
  recibido: {
    label: 'Recibido',
    description: 'El reclamo ingresó a la plataforma y aguarda revisión inicial comunitaria.',
    color: '#64748B',
    bg: '#F1F5F9',
    text: '#334155',
    border: '#CBD5E1',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-300',
    stepIndex: 1,
  },
  en_revision: {
    label: 'En revisión',
    description: 'La coordinación vecinal está evaluando la información y evidencia presentada.',
    color: '#D97706',
    bg: '#FEF3C7',
    text: '#92400E',
    border: '#FCD34D',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-300',
    stepIndex: 2,
  },
  validado: {
    label: 'Validado',
    description: 'La problemática fue constatada y clasificada para el seguimiento territorial.',
    color: '#0284C7',
    bg: '#EFF6FF',
    text: '#0369A1',
    border: '#BAE6FD',
    badgeClass: 'bg-sky-100 text-sky-800 border-sky-300',
    stepIndex: 3,
  },
  derivado: {
    label: 'Derivado para gestión',
    description: 'Se organizó la solicitud en petitorio vecinal y se canalizó ante las dependencias correspondientes.',
    color: '#0B4F8A',
    bg: '#F0F7FF',
    text: '#072C4F',
    border: '#BFDBFE',
    badgeClass: 'bg-blue-100 text-blue-800 border-blue-300',
    stepIndex: 4,
  },
  en_seguimiento: {
    label: 'En seguimiento',
    description: 'Monitoreo activo de avances, reclamos comunitarios y estado de la gestión.',
    color: '#0284C7',
    bg: '#F0F9FF',
    text: '#0C4A6E',
    border: '#7DD3FC',
    badgeClass: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    stepIndex: 5,
  },
  resuelto: {
    label: 'Resuelto',
    description: 'La problemática cuenta con resolución efectiva documentada y verificada.',
    color: '#059669',
    bg: '#ECFDF5',
    text: '#065F46',
    border: '#A7F3D0',
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    stepIndex: 6,
  },
  cerrado: {
    label: 'Cerrado',
    description: 'El reclamo fue archivado tras conclusión del trámite o derivación final.',
    color: '#4B5563',
    bg: '#F3F4F6',
    text: '#1F2937',
    border: '#E5E7EB',
    badgeClass: 'bg-gray-100 text-gray-700 border-gray-300',
    stepIndex: 7,
  },
};
